version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.16.6

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify -Pcoverage
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - run:
          name: Analyze on SonarCloud
          command: mvn sonar:sonar
      - coverage-reporter/send_report:
          project-token: $CODACY_PROJECT_TOKEN
          coverage-reports: target/site/jacoco/jacoco.xml
      - run:
          name: Install Selenium-side-runner and ChromeDriver
          command: |
            npm install -g selenium-side-runner
            npm install -g chromedriver
      - run:
          name: Install SQLite3
          command: sudo apt-get update && sudo apt-get install -y sqlite3
      - run:
          name: Run SQLite3 migrations
          command: sqlite3 universe.db < src/main/resources/migrations/2023_02_20_000000_create_tables.sql
      - run:
          name: Start application
          command: java -jar target/universe.jar application.properties
          background: true
      - run:
          name: Run Selenium IDE test
          command: selenium-side-runner src/test/universe.side

workflows:
  build-and-test:
    jobs:
      - build:
          context: SonarCloud