version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.16.6
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-browsers
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify -Pcoverage
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - run:
          name: Analyze on SonarCloud
          command: mvn sonar:sonar
      - coverage-reporter/send_report:
          project-token: $CODACY_PROJECT_TOKEN
          coverage-reports: target/site/jacoco/jacoco.xml
      - browser-tools/install-chrome:
          replace-existing: true
      - browser-tools/install-chromedriver
      - run:
          name: Install Selenium-side-runner
          command: sudo npm install -g selenium-side-runner
      - run:
          name: Install SQLite3
          command: sudo apt-get update && sudo apt-get install -y sqlite3
      - run:
          name: Run SQLite3 migrations
          command: sqlite3 universe.db < src/main/resources/migrations/2023_02_20_000000_create_tables.sql
      - run:
          name: Start application
          command: java -jar target/universe.jar application.properties
          background: true
      - run:
          name: Run Selenium IDE test
          command: selenium-side-runner src/test/universe.side
      - run:
          command: |
            echo 'export HAWK_VERSION=$(curl -o- https://api.stackhawk.com/hawkscan/version)' >> "$BASH_ENV"
            echo 'export PATH="hawk-${HAWK_VERSION}:${PATH}"' >> "$BASH_ENV"
      - run: curl -v https://download.stackhawk.com/hawk/cli/hawk-"${HAWK_VERSION}".zip -o hawk.zip
      - run: unzip hawk.zip
      - run: npm install
      - run: nohup npm run start &
      - run: hawk --api-key="${HAWK_API_KEY}" scan --env CIRCLE_SHA1="$CIRCLE_SHA1" --env CIRCLE_BRANCH="$CIRCLE_BRANCH" stackhawk.yml
  semgrep-full-scan:
    docker:
      - image: semgrep/semgrep
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/daredevil2033/universe.git
    steps:
      - checkout
      - run:
          name: Semgrep full scan
          command: semgrep ci
  semgrep-diff-scan:
    parameters:
      default_branch:
        type: string
        default: master
    docker:
      - image: semgrep/semgrep
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/daredevil2033/universe.git
    steps:
      - checkout
      - run:
          name: Semgrep diff scan
          environment:
            SEMGREP_BASELINE_REF: << parameters.default_branch >>
          command: semgrep ci

workflows:
  build-and-test:
    jobs:
      - build:
          context: SonarCloud
  semgrep:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: master
          context: SonarCloud
      - semgrep-diff-scan:
          filters:
            branches:
              ignore: master
          context: SonarCloud