version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.16.6

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - run:
          name: Analyze on SonarCloud
          command: mvn sonar:sonar -Pcoverage
      - coverage-reporter/send_report:
          project-token: $CODACY_PROJECT_TOKEN
          coverage-reports: target/site/jacoco/jacoco.xml

workflows:
  build-and-test:
    jobs:
      - build:
          context: SonarCloud